// Generates src/buildConstants.generated.ts from process.env.
// Runs as part of `pnpm build`. CI sets RELAY_URL/RELAY_SECRET via env;
// dev runs without env vars produce empty constants (resolved at runtime instead).

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const out = path.resolve(__dirname, '../src/buildConstants.generated.ts');

const url = process.env.RELAY_URL || '';
const secret = process.env.RELAY_SECRET || '';

const content = `// AUTO-GENERATED by scripts/prebuild.mjs — do not edit.
export const BUILD_RELAY_URL = ${JSON.stringify(url)};
export const BUILD_RELAY_SECRET = ${JSON.stringify(secret)};
`;

fs.writeFileSync(out, content);
console.log(`[prebuild] buildConstants.generated.ts: URL=${url.length} chars, SECRET=${secret.length} chars`);
